name: embla_io_website
description: The website for Embla (embla.io)
version: 0.0.1
environment:
  sdk: '>=1.13.0 <2.0.0'
dependencies:
  browser: ^0.10.0
  dart_to_js_script_rewriter: ^0.1.0
  sass: ^0.4.2
  markdown: ^0.9.0
  mustache: ^0.2.5
transformers:
- dart_to_js_script_rewriter
- sass
